name: tests-front

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: cd frontend && yarn

      - name: Run ESLint
        run: cd frontend && yarn lint

      - name: Test TypeScript Syntax
        run: cd frontend && yarn type-check

      - name: Build
        run: cd frontend && yarn build
